### PR TITLE
Fix slashes in paths on Windows

### PR DESCRIPTION
**Pull request by michaelmior**
Currently things break in bash on Windows because the cwd and the current path use different types of slashes and eventually the globby test shows that they are in different directories.
This just normalizes the slashes for both paths so it won't cause issues later.

### CODE REVIEW

**Comment by tclindner** [comment]
Hey @michaelmior! Thank you for opening a PR! I’ll get a release cut tomorrow. Before I merge I would like to review some recent changes that were done for globby. I recall that we hit something like this before.

Is it possible to solve this without introducing a module?

**Comment by michaelmior** [comment]
I think that's a good question :) I generally like to avoid introducing new modules as well. In this case, globby itself already uses slash so it will be installed anyway. That said, slash is basically one function which is relatively short so I'm sure that relevant logic could be extracted.

What would be even nicer is if we could guarantee that both paths were generated in the same format in the first place.

**Comment by tclindner** [comment]
Thank you! I’ll get the release cut tomorrow. Thank you again for taking the time to open a PR. I appreciate it!

**Comment by michaelmior** [comment]
Thanks!

**Comment by tclindner** [comment]
@michaelmior [`v4.5.1`](https://github.com/tclindner/npm-package-json-lint/releases/tag/v4.5.1) has been released. Thank you again for opening a PR 🎉 🙌

**Comment by michaelmior** [comment]
Thanks again!

**Pull request merged**
