### PR TITLE
feat: export write method

### PR DESCRIPTION
**Pull request by dangreen**
**Description of change**

I need the `write` method to implement a custom executable script.

**Checklist**

  - [ ] Unit tests have been added
  - [ ] Specific notes for documentation, if applicable

### CODE REVIEW

**Comment by dangreen** [comment]
@tclindner Hi. Review pls 🙏

**Comment by dangreen** [comment]
@tclindner ping

**Review by tclindner — APPROVED** [review]

**Comment by tclindner** [comment]
Thank you! Would you mind adding a quick test for coverage.

**Comment by dangreen** [comment]
@tclindner Done

**Comment by tclindner** [comment]
Released!

**Comment by dangreen** [comment]
@tclindner Thanks!

**Pull request merged**
